### ISSUE TITLE
Change CBC mode

### ISSUE THREAD

**Issue by Crusader4Christ** [andymckay/m2secret#2]
How can I change mode to ECB?

**Comment by EnTeQuAk** [comment]
May I kindly ask why you'd want to do that? There isn't an easy way that doesn't require patching the library so pull requests are happily welcome but please note that this library isn't actively maintained (only to a level of survival) at the moment. Also, most recent work from https://github.com/EnTeQuAk/m2secret is about to be merged soon so quite a few things will change.
